export const LOGIN_SERVICE_URL = '/users/login'
export const REGISTER_SERVICE_URL = '/users/register'
export const LOGOUT_SERVICE_URL = '/users/logout'
export const CAR_SERVICE = '/cars'
export const GET_CARS_SERVICE = '/cars/all'
