export { default as redirectReducer } from './redirectReducer'
export { default as logInReducer } from './login.reducer'
export { default as removeCarReducer } from './remove-car.reducer'
export { default as editCarReducer } from './edit-car.reducer'
export { default as getCarsReducer } from './get-cars.reducer'
export { default as createCarReducer } from './create-car.reducer'
