export const CarsTypes = {
  GET_CARS_START: 'GET_CARS_START',
  GET_CARS_SUCCESS: 'GET_CARS_SUCCESS',
  GET_CARS_FAIL: 'GET_CARS_FAIL',
  CREATE_CAR_START: 'CREATE_CAR_START',
  CREATE_CAR_SUCCESS: 'CREATE_CAR_SUCCESS',
  CREATE_CAR_FAIL: 'CREATE_CAR_FAIL',
  EDIT_CAR_START: 'EDIT_CAR_START',
  EDIT_CAR_SUCCESS: 'EDIT_CAR_SUCCESS',
  EDIT_CAR_FAIL: 'EDIT_CAR_FAIL',
  REMOVE_CAR_START: 'REMOVE_CAR_START',
  REMOVE_CAR_SUCCESS: 'REMOVE_CAR_SUCCESS',
  REMOVE_CAR_FAIL: 'REMOVE_CAR_FAIL',
}
